
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]
