

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "link-arg=-s"]

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "link-arg=-s"]

[target.armv5te-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "link-arg=-s"]

[target.armv5te-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "link-arg=-s"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabi-gcc-4.7"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]


