
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.armv7-unknown-linux-musleabi]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.x86_64-unknown-freebsd]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.arm-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]

[target.armv5te-unknown-linux-musleabi]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s"]
