name: Build multi-architecture binaries

on:
  push:
    tags:
      - '*'

jobs:
  setup:
    name: Prepare build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v3
        with:
          repository: cloudflare/boringtun
          ref: boringtun-cli-0.5.2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, x86_64-unknown-linux-gnu
      - name: Install Cross for Cargo
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
  build:
    needs: setup
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Compile Binaries
        run: |
          mkdir -p dist
          cross build --release --target=aarch64-unknown-linux-gnu
          XZ_OPT=-9 tar -C target/aarch64-unknown-linux-gnu/release -Jcvf dist/boringtun-cli-0.5.2-aarch64-unknown-linux-gnu.tar.xz boringtun-cli
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/boringtun-cli-0.5.2-aarch64-unknown-linux-gnu.tar.xz
