name: Build multi-architecture binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v3
        with:
          repository: cloudflare/boringtun
          ref: boringtun-cli-0.5.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/boringtun-cli
      - name: Determine Image ID and Version
        id: image_id
        run: |
          mkdir -p dist
          XZ_OPT=-9 tar -C target/${{ matrix.target }}/release -Jcvf dist/boringtun-cli-0.5.2-${{ matrix.target }}.tar.xz boringtun-cli
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: dist/boringtun-cli-0.5.2-${{ matrix.target }}.tar.xz
  push:
    name: Push release artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: aarch64-unknown-linux-gnu
      - uses: actions/download-artifact@v3
        with:
          name: armv7-unknown-linux-gnueabihf
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/boringtun-cli-0.5.2-aarch64-unknown-linux-gnu.tar.xz
            dist/boringtun-cli-0.5.2-rmv7-unknown-linux-gnueabihf.tar.xz
            dist/boringtun-cli-0.5.2-x86_64-unknown-linux-gnu.tar.xz
