name: Build multi-architecture binaries

on:
  push:
    tags:
      - '*'

env:
  TARGETS: "aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl,armv7-unknown-linux-gnueabihf,armv7-unknown-linux-musleabi,armv7-unknown-linux-musleabihf,x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl,mips-unknown-linux-gnu,arm-unknown-linux-gnueabihf,armv5te-unknown-linux-musleabi"

jobs:
  prepare:
    name: Prepare local assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local
        uses: actions/checkout@v3
      - name: Make assets available
        uses: actions/upload-artifact@v3
        with:
          name: config-append.toml
          path: config-append.toml
  build:
    name: Build Binaries
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v3
        with:
          repository: cloudflare/boringtun
          ref: boringtun-cli-0.5.2
      - name: Get local assets
        uses: actions/download-artifact@v3
        with:
          name: config-append.toml
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ env.TARGETS }}
      - name: Install Cross for Cargo
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Compile Binaries
        run: |
          cat config-append.toml >> ~/.cargo/config.toml

          mkdir -p dist

          for TARGET in ${TARGETS//,/ }
          do
            cross build --release --target=${TARGET}
            XZ_OPT=-9 tar -C target/${TARGET}/release -Jcvf dist/boringtun-cli-0.5.2-${TARGET}.tar.xz boringtun-cli
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
