name: Build multi-architecture binaries

on:
  push:
    tags:
      - '*'

env:
  TARGETS: "aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl,armv7-unknown-linux-gnueabihf,x86_64-unknown-linux-gnu,x86_64-unknown-linux-musl"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout boringtun
        uses: actions/checkout@v3
        with:
          repository: cloudflare/boringtun
          ref: boringtun-cli-0.5.2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ env.TARGETS }}
      - name: Install Cross for Cargo
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Compile Binaries
        run: |
          mkdir -p dist

          for TARGET in ${TARGETS//,/ }
          do
            cross build --release --target=${TARGET}
            XZ_OPT=-9 tar -C target/${TARGET}/release -Jcvf dist/boringtun-cli-0.5.2-${TARGET}.tar.xz boringtun-cli
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
